name: "Java CI with Maven - Test and package"
on:
  pull_request:
     branches:
      - main
jobs:
  Main_job:
   name: Main_job
   runs-on: ubuntu-latest
   steps:
    - name: checkout
      run: actions/checkout@v4
    - name: setup_java
      run: actions/setup-java@v4
    - name: build
      run: mvn -B package
