name: "Java CI with Maven - Test and package"
on: pull_request
jobs:
  Main_job:
   name: Main_job
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
    - name: build
      run: mvn -B package
