name: "Java CI with Maven - Test and package"
on:
  pull_request:
    branches:
      - main
jobs:
  Main_job:
   name: Main_job
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository }}"
    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
    - name: cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.maven/caches
          ~/.maven/wrapper
    - name: build
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')
