on:
  pull_request:
    types:
      - closed

jobs:
  boc_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: doc
      run: mvn -B javadoc::javadoc
    - name: page
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.SA_MERE }}
        publish_dir: ./target/reports/apidocs

